# Configuration file for pre-commit (https://pre-commit.com/)

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        stages: [pre-commit]
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: system
        stages: [pre-commit]
        types: [python]
