language: python
python:
  - '3.5'
  - '3.6'
branches:
  only:
    - master
install:
  - python3 setup.py install
  - pip install codecov
script:
  - cd $TRAVIS_BUILD_DIR/tests
  - coverage3 run --source=metadata_updater tests.py
after_success:
  - codecov
env:
  matrix:
    secure: N55zGNrRCOTu/kQx6257la3XY+zfch+onflVKqrsalbR9vj4qnB4PyFNue71xFZijMVGJ7vn9hKBgkjUy8j936hSzdN2KmudjSr759CDtOtPNN/9sKE+d08s89o56C40vnRvCS8H0CrLI7R7zNRoeC67EW1XZlZPwp/eBSqUF5kPkxwmC7AilK6fDjI27gpjNhyt2EvhhA63eCYsP3KgBM5iBurq2C1QZcBC8nkfL+RtrrLDbii69bUAb3kcmOKpaxZ1JJi3FZ9MflAp2wV1Vvy355kgVNbEzkUEKwFIGhqiRsLfr9qQ3WRbGkZs9O27B4MdcafJ+599eXvB9t9/td7iWMvl+IbwQMzXQHfX2K0p2Kf1caQy844k66boRDf4pM/7oclTygpmqJ0bgn8VVoxT3yWPT9Zx2l9ziZPlrJLxydbr1K8tIHqTaKRRPI/2IB0gihTyzgDT40z8Yxti75Z+qCZhXd1GzmOUV2OFIGSEZa/R3GIUqGzS2S7zUHAUnWsOGCIbPEWlmDpXSC1KYv7eTBELy5DSaXW54sMbWN0PIyO/Ca5wMKp0hJyqiTinDb8cARr2GcFmAVQVF56nVOlI4a+MP7x+BDCUqqP49frXHAcxORD451MZiWhl03aIu3RjQcCxhaz5D3nwomlPmOy+f9OFImKsNzfJQs7PfSg=
