language: python
python:
- '3.5'
- '3.6'
branches:
  only:
  - development
install:
- python3 setup.py install
- pip install codecov
script:
- cd $TRAVIS_BUILD_DIR/tests
- coverage3 run --source=metadata_updater tests.py
after_success:
- codecov
env:
  matrix:
    secure: E7a3Fv7KugNqfxFQbMTCHn9mQITvp6DjASZUvnh9ZYGzNkSh3l0SBVU8UmGoFrIui4gYwB3ztyfg0PP4mONvihvS3w4nY0fNPAqCUCZSq/13wLPmzgdBlOIP7j7yklu0lhBVipEJx5r6w0PnefjAVPpZA+lsGpmAdrPHZxn/b15uEnE5lYU22Y6Qfsqpi1FJWgc20aQS4y1Z9ibF3zht6CxdppbYM5SCrn7XRrDJwNDAZudCs7RZzvczdH+jVQ9mCT4yzMXibTbPpjguj0S4Lj61714a3zMW+35qZpJ+mDmyy4KpBCi1ZqKSF2oSPa30e9/dWHf/tb6oN3FTKt9yd0ZZiOIxCNbJ7DmfVQf78Mfc2obzUay2YecUNXOlfck+qZhJFdnI0oI4xgIy7kiOKFogRt2PdHua0LsndKuNlFuZxlB7asMETkSLe7+aDN4miKUc52otP2uuMiUcGsO1sqqI4FWWXbiQZChnE9kn0xnn8TC2hhURGqRyK1qAFeHKZlR5Dw4Ty2AC069SVxDHoRZqZngvi1HDhEy4SE2Jb9a2s60ABzEl6zQfW9w8yi9etUY1S87sxcYh52QtLWfCtp85q0/PCMXeBPU0khYt5L50CUYcmouENwlhf11G/YTFxObEN4cJePGru7n4hSJvJboKpQNuhaiBOT61Y+mYosk=
