language: python

python:
  - "3.5"
  - "3.6"

branches:
  only:
    - development

install:
  - python3 setup.py install

# Fails without script section
script: 
  - cd $TRAVIS_BUILD_DIR/tests
  - python3 /test_metadata_updater.py
