language: python
python:
- '3.5'
- '3.6'
branches:
  only:
  - development
install:
- python3 setup.py install
- pip install codecov
script:
- cd $TRAVIS_BUILD_DIR/tests
- coverage3 run --source=metadata_updater tests.py
after_success:
- codecov
env:
  matrix:
    secure: LeoV3eI2BlwjpnOUaTH9p7UW+lR96AztQ32r1nF32o8sXDmc1cQ5DfVIlsYl+c/CdtwiDAbsovvlukdV6hAtoX3frqax8QfmNxmO+dtvunD8bVG0chJnDVlNOEulOSlv0iklSCkMB03SiJbUd/A0SfbZygtdphaaYbMaMtuvPuygpDtC/A0heLjN3I7NLMnE1k9MGSxhlpMQ3ByGxcDDh4WCCDUfsYZtNXnO6NF0BBD9LDkDJlqDNCjgo/MyQOvKB1wfhyv+88JLWEoVb3xX/ZmMou1cr4+7l0jUkH+yVGIj4qGMWed9+RiZIEqUaZKKeRG6zDhYCDeh+kOXofrNGZW9JLqQ0GNXjckklefrPT3X/YLpMv8OBm6qtUC83cVPtM5GzHjPmK0Hn3V9CGfA3qmWzpe/1ZNNcPXMPF9VeUezAfa4nKfuOkIU7Ua9s1hmlb6awQahV3R/6Fy+fpMovW5ZfbsW7k4j/yzKoSXTltM2P1nP2I+6ulKUQwGw8SCOmre1ZnWhtuFw0kbnkXxrIr+3pN3Ovo2XpiDN6OxCRMcFO9cyIDNVaebF/zWoJkWHZasXgDl7TJkVBaAPQ728+6fAnkMSJ+tfYBJrc8PWckqbRHPYeS6+9lqwtfl/vWw6zlksCRgjBrEVRFnOaVGxDOUQsBzStamfngijZRk/CWw=
