language: python
python:
- '3.5'
- '3.6'
branches:
  only:
  - development
install:
- python3 setup.py install
- pip install codecov
script:
- cd $TRAVIS_BUILD_DIR/tests
- coverage3 run --source=metadata_updater tests.py
after_success:
- codecov
env:
  global:
    secure: YCD7RE4tg488+AS3++lKiWHH2ZZo5X0d2u87sifO547wMuYZ09LuKbqIQcLO6Dgm4abCUXDG/FKzPRbPndu2i1qVDnd85bD0HhPdTT9+Rhdni1R2jgjF2fMZ7bmrScuEofv8mqdQ2D01+x8RBg3B7JcGhH3udEuXlHHgEpDYuAu/fYD5obcxgnStScT8oZBGhi/Mt+vLh5Q10Zht3dqSZ3Mz0q7iQ95jARzpuSqmWR7Wx909gAlogUCn75JIVK2bm7GBxnWNZ8xE7OLna8VvX9JbsFesiPdVwD6UvrWaFoKYmsem2WrCrkDK8yJ/0elXkXNpE1mSNpQWkdodgrkTmFX7w4el2Nk9cELmD4ywzl7u8J5NrXhWRwLUdIjWPB9yUtdcVQrau3Czp0ZBHdBt0fPYQ/mRrReF3+m3L/kjHjanJW/R5IiWekIH39bbU2wNmQ5F6M86/iNtsr1HUTLluJeKz4IV/ID0kT158qMoMy5u3NyC3MePsH0yn8qzfvtwl/GaZGb0AOH5NAojuLKQPe4j3GMMqV2eyuTbx2OVdR7UZmXojI+UgKAIrRJs/09Rdlwv7m7FVGix4rAEuHfVXSPtewKb62ggWbI2SYtHnU8fqsR8LLnO++nrLm7CPcB7x4RzPdgfmLqsV+5HlK04iXGgA8Nj9kWpIWzg5Ss0boU=
