language: python
python:
- '3.5'
- '3.6'
branches:
  only:
  - development
install:
- python3 setup.py install
- pip install codecov
script:
- cd $TRAVIS_BUILD_DIR/tests
- coverage3 run --source=metadata_updater tests.py
after_success:
- codecov
env:
  matrix:
    secure: BeGLMZUUGVvNkLvnSQF39QNmEH8V1xJ4IiDd5b+hjp4TvaUE9d9omv3bsrEyAbwghpDUS6Af5R3XIjEAU2grWzOZB2wgSvDPGQ4ZqlvLY2c7b8PAkh0OQ2UdbYTqMgqAQHN/wh6IB92cf6ZEUxtpCLcO9V4V4CBKX6mNOWqSJHP7/jFilcqZSXqQN71VfmA7oNki41UIhw3ao+uEn0jGrQZpAkRDDiaBBg/UCsu77J33rODD1WPINoNgiIKjY1QfLj/N/2GDAdxJK/Qpn22swBBKfgdkoqXngylNG0dlv4OehwReveCI4fqg9HP+C0lulhF+Bv2X5/hnDLEkMP3l2Drb8MmBUAjFnNrepPEUdGCCIqGEKyHZcxDyj9kru/JIB0ppQ1j5Vqc5vTm55/mTA5wH8gZheMCqPsi7F+32yo9QmosCHU8p0fdyXfJXeZ7JplOdXW+pZ8WVJS9Bt7P06ow54ffdlXRYjN6Y+rw7kcCFrf68IIKQNt/5wzQaqJ8OVzpzI5ZIDdDX8SgKfK/2fcsUAk2by+uNNOInOrFYEefoiyvkoP2bVXNYdWJbyq6AK/BPI5Mkxw2uA0XsB/aNgluDnIGjlQH+qimmbmdQhnKd9Ds+hOau0LKZpnc9+pqXIMEhr6esY+6HKrtJLZrjBOOpfc/j8AX7gYJJ/sEC2h8=
