language: python
python:
  - '3.5'
  - '3.6'
branches:
  only:
    - master
install:
  - python3 setup.py install
  - pip install codecov
script:
  - cd $TRAVIS_BUILD_DIR/tests
  - coverage3 run --source=metadata_updater tests.py
env:
  matrix:
    secure: iYskVypsTC1KSuAZA1KLOSFVAHCpDRNUyKjs50DjJgxmzIIFMz3nyyCKe3PRNCMrKdW+wxvYmrab+98Gj/tcuniKPmhWeFcyEWKz1fsJyLydPLliMug5QF9yZVcUZSrRwD+5UeUXR7bNTXGpfdnK08DkhhAuSwgFsINhBRc96b2B97q6sTQuhNahpb15FoUeMm+b2KofYFUKcSdDWdCOWIHhKbF8hp47CcNruygpt9Akm2BvnCstEAlHqrcXXuX3bKCkAeWO4MqsG04azz8S17bosJ57ilxf5AKIYVMK13gX9zaRXZE7rRuG/Lqhd5k/6ddHikY9zXIRWsCzhbyAfDsvXE5MDsY0WB/OSibKGdQjI57jUwUqJGm12Bc6bjvLgd6pUHoH5pcrSVizrdGE+fA8HmG9Nvsk6HJvviE+/f0pf00SEX58aBf/iHDRt1ANYFyiMbGOZqcs0s3y+tYa4FFUvMKYfvWUDh62t2HZWbwc9lYzLdMrLvMdgvWfLPdy7WFY9Hx7rcF1T1G5Fa7rdc/pGYWhYiScjVank5HMPA4DDy8YlF7b755feD8evQh3T0lv0cfv2p2sMGelr2rLVs1TIgzcAv5L6SWpE3r35ins5ZbfD4DjCI1R79DEI61ilYinkLPdXmSGinvClT5/9cUNIkXxauFETigE3tsPhFE=
