language: python

python:
  - '3.5'
  - '3.6'

branches:
  only:
    - development

install:
  - python3 setup.py install
  - pip install codecov

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - coverage3 run --source=metadata_updater tests.py

after_success:
  - codecov

env:
  matrix:
    secure: CwSTAWiJH1fRSYNNQIfSzu7lIYe933AQJrenJm+89oqoREZyzG9+jHf5sXTN//HcGiSMKaB8R+okPrVUcutUp1JYM5HTMU5ZMcJacwDyzLjnehdZq2SrK2YQ8GKxCkSSXkhxTWiCqMyt5hEYVToRy6c8V1Spn9W7CJnTwy58r8EPv+OAy15VMLAQo1fyHRyfYbxXg847mcN06/1vrYObxigomqtPGYLmS/Rgyk4A+iEKTdEgArlGylHJjdun1V64TS9zhrr3xFAA7G+SnHIKbq0lGVWW02+ASECl9gEI1IpGfGdYVB9JB9I4qUp6su6cUwoC8kmaI74F0yZ8SAD1g8QvUAtoeYw0oGYZTP8pR/rlpZx/M/M7SimoS23GSL36EyozPAvgYolSX9s/EteH10jhl5hKe8fXd1XmaEe+BrnDnX4F/HDsAukIRbZ3lLqCcxgZ3MXa2LKPCIeeeOAEZ6FxS8iyZzn8QTVvtNMS+ci0usR6540z83O13KPFeCedsQS6LyKIeCWaIlXqup/godRsMAwlVysEi5P8m3W0zbS/y/tXCCR06F5OLwnWwpd99ajteHJoNTQghROaRoQ0YLExK5973VCd223gF0HOdhxBRE5IrodjG11bwf8R4Td09yPhU7oqoNZHEgh0aGrtw4Bc37OsNWfiAho6loBJlVk=
