language: python
python:
- '3.5'
- '3.6'
branches:
  only:
  - development
install:
- python3 setup.py install
- pip install codecov
script:
- cd $TRAVIS_BUILD_DIR/tests
- coverage3 run --source=metadata_updater tests.py
after_success:
- codecov
env:
  global:
    secure: LYkAs5TxIi45caXUJOQfvMCrL776XnC0dB1NW1+VtgCQZ2NNULhic9Rcf0G0yVMqLsOFU+naZBcxILVjY8jK7ddMlnXJK2LQmuY02qRInsQfAbcHiOc5TF8Cj6LptBtLw2c5xz4MlzLh6mFCQ7VHiq2DtgcTVukyvjFwHq8veEdvYqZdEOcQShSeYA97JzvTN9b1rElpx5Ivij+bHAEifNhk/+9qCDiUwvztRTvDScURLocI/I8o/4PU2R1WPqT9T6lyiB9GvZc7NAONdEbxqqpWGUj/6Ioz9xU8jcqsT7/KuF5NYWylO4uok8BcOr6/ManEIPkhH11x5XG6ucjBnet25Vg5bkZ4jTX5L5q5h/bjpJsSz2APqvbE0i6ApJab1Twypf2Ddlar49BDJTWl7XANkSHO3SVs7B2NshDCXWfSkEFKGRfT3bjPvuofzIFoRp3B9tkJcLCPd/9GZDZ4NNgcINocEVBjSlPPwMBxbr27Uu+1Zvi5w0JFhgPj/MX2YQQCLipOodXLt01WlTBxSRtPlobPK8akzKIBhUXHu/kmzLBoJphAx4Xbf+a8HXUdYbg8fHlD8T/le9QzuCEzV+EFRHOWM09OZjYPh9TcwI/XReFaxxd5tDDvPqga+rgASKeP7WMJrv5a8T1OQgQVLbPcRCDFA0PlHvK36uHaF+Y=
