name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  test:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            python:
              - "3.5"
              - "3.6"
            os:
              - ubuntu-18.04
    env:
      PG: 10
      APT: "apt-get -o Dpkg::Progress=0 -o Dpkg::Use-Pty=0"
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade codecov setuptools
    - name: Install
      run: |
        python setup.py install
    - name: Run tests
      run: |
        cd tests
        coverage run --source=metadata_updater tests.py
