name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  test:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            python:
              - "3.6"
              - "3.7"
              - "3.8"
              - "3.9"
              - "3.10"
              - "3.11"
            os:
              - ubuntu-latest
    env:
      PG: 14
      APT: "apt-get -o Dpkg::Progress=0 -o Dpkg::Use-Pty=0"
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
    - name: Install
      run: |
        python setup.py install
    - name: Run tests
      run: |
        cd tests
        python -m unittest tests
